"""add applied_sim_time to decisions

Revision ID: 32116025d2fc
Revises: 76cd7af73eea
Create Date: 2026-09-16 11:23:16.154292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32116025d2fc'
down_revision: Union[str, Sequence[str], None] = '76cd7af73eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('applied_sim_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'applied_sim_time')
    # ### end Alembic commands ###
