"""add summary to runs

Revision ID: 4f233553e441
Revises: fea74b9267ba
Create Date: 2026-09-14 23:48:16.679166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4f233553e441'
down_revision: Union[str, Sequence[str], None] = 'fea74b9267ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'summary')
    # ### end Alembic commands ###
