"""add final_action to decisions

Revision ID: 76cd7af73eea
Revises: 4f233553e441
Create Date: 2026-09-16 11:17:17.835115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '76cd7af73eea'
down_revision: Union[str, Sequence[str], None] = '4f233553e441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('final_action_type', sa.String(), nullable=True))
    op.add_column('decisions', sa.Column('final_action_params', postgresql.JSONB(astext_type=sa.Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'final_action_params')
    op.drop_column('decisions', 'final_action_type')
    # ### end Alembic commands ###
