"""init

Revision ID: fea74b9267ba
Revises: 
Create Date: 2026-09-10 08:56:09.696104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# Alembic autogenerate does not know how to import custom types on its own
# (a known limitation) -- it emitted `sumo_agents.obs.models.GUID()` below
# without this import, which would fail with NameError at runtime.
import sumo_agents.obs.models

# revision identifiers, used by Alembic.
revision: str = 'fea74b9267ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('run_id', sumo_agents.obs.models.GUID(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('git_sha', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sumo_agents.obs.models.GUID(), nullable=False),
    sa.Column('sim_time', sa.Float(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('junction_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=False),
    sa.Column('validator_status', sa.String(), nullable=False),
    sa.Column('validator_violations', postgresql.JSONB(astext_type=sa.Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('supervisor_verdict', sa.String(), nullable=True),
    sa.Column('supervisor_reason', sa.Text(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('effect', postgresql.JSONB(astext_type=sa.Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_run_junction', 'decisions', ['run_id', 'junction_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sumo_agents.obs.models.GUID(), nullable=False),
    sa.Column('sim_time', sa.Float(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('effort', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_calls_run_role', 'llm_calls', ['run_id', 'role'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sumo_agents.obs.models.GUID(), nullable=False),
    sa.Column('sim_time', sa.Float(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.SmallInteger(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('recipients', postgresql.ARRAY(sa.String()).with_variant(sqlite.JSON(), 'sqlite'), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_run_cycle', 'messages', ['run_id', 'cycle_id'], unique=False)
    op.create_table('metrics',
    sa.Column('run_id', sumo_agents.obs.models.GUID(), nullable=False),
    sa.Column('sim_time', sa.Float(), nullable=False),
    sa.Column('junction_id', sa.String(), nullable=False),
    sa.Column('mean_waiting_s', sa.Float(), nullable=True),
    sa.Column('queue_len', sa.Integer(), nullable=True),
    sa.Column('throughput', sa.Integer(), nullable=True),
    sa.Column('mean_speed', sa.Float(), nullable=True),
    sa.Column('co2_mg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'sim_time', 'junction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_index('ix_messages_run_cycle', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_llm_calls_run_role', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index('ix_decisions_run_junction', table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('runs')
    # ### end Alembic commands ###
